# Generated by Django 4.1.5 on 2023-01-21 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='funding_deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 11, 8, 30, 899065)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='is_funded',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='max_age',
            field=models.IntegerField(default=119),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='max_minutes',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='max_players',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='min_age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='min_minutes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='min_players',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
