# Generated by Django 4.1.5 on 2023-01-26 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_images_project_pledges_total_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
