# Generated by Django 4.1.5 on 2023-01-26 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pledges_total',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='projects.images'),
        ),
    ]
