# Generated by Django 4.1.5 on 2023-01-26 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_pledges_total_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='name',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='projects.project'),
        ),
    ]
