# Generated by Django 4.1.5 on 2023-01-26 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_rename_name_images_image_url_remove_project_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={},
        ),
    ]
