# Generated by Django 4.1.5 on 2023-01-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'images'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_funded',
        ),
    ]
