# Generated by Django 4.1.5 on 2023-01-27 23:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0013_alter_categories_options_alter_images_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='favourited_by',
            field=models.ManyToManyField(blank=True, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
