# Generated by Django 4.1.5 on 2023-04-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_thumbnail_image_alter_images_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
